const OTHER_CHARACTERS = ",.!? ()0123456789";
const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
export const EXTENDED_ALPHABET = ALPHABET + OTHER_CHARACTERS;
export const LETTER_COMBINATIONS_AMOUNT = 5;
